name: CI - Docker

on:
  push:
    branches:
      - feature/allow-run-as-container
      - main
    tags:
      - '*'

  release:
    types:
      - published

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - uses: e1himself/goss-installation-action@v1
        with:
          version: 'v0.4.4'

      - name: Build image
        run: docker build -t tannguyen04/shellvar:test-shellvar .

      - name: Show images information
        run: docker images

      - name: Test image
        run: dgoss run tannguyen04/shellvar:test-shellvar tail -f /dev/null

  deploy-on-release-tag:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Images & Deploy
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
            year=$(git log -1 --format=%cd --date=format:%y)
            echo "Year: $year"
            month=$(git log -1 --format=%cd --date=format:%m)
            echo "Month: $month"
            month_without_zero=$(git log -1 --format=%cd --date=format:%-m)
            echo "Month without zero: $month_without_zero"
            target_month="$year-$month"
            echo "Target month: $target_month"
          
            response=$(curl -s "https://api.github.com/repos/tannguyen04/shellvar/releases")
            # Check request success.
            if [[ $(echo "$response" | jq -r .message) == "Not Found" ]]; then
              echo "Repository does not existing."
              exit 1
            fi
            # Count release.
            release_count=$(echo "$response" | jq --arg YEAR "$year" --arg MONTH "$month" -r \
            '. | map(select(.published_at | startswith("\($YEAR)-\($MONTH)"))) | length')
            echo "Number of releases in $target_month: $release_count"
        
            version="${year}.${month_without_zero}.${release_count}"
            echo "Image version: $version"
            
            # Build images.
            docker build -t tannguyen04/shellvar:latest .
            docker build -t "tannguyen04/shellvar:${version}" .
          
            # Show docker images
            docker images
          
            # Push docker to Docker Hub.
            docker push tannguyen04/shellvar:latest
            docker push "tannguyen04/shellvar:${version}"

  deploy-on-push-main:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    if: ${{ github.ref == 'refs/heads/feature/allow-run-as-container' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Images & Deploy
        run: |
          docker build -t tannguyen04/shellvar:canary .
          # Show docker images
          docker images


